<?php /** @var $block \Speroteck\Newsblock\Block\NewsblockList */ ?>
<h1><?php echo __('Latest News') ?></h1>
<ul class="newsblock-list">
<?php /** @var $post \Speroteck\Newsblock\Model\Newsblock */ ?>
<?php
    $newsblocks = $block->getNews();
    $newsBlockData = array();
    foreach ($newsblocks as $newsblock) {
        $newsBlockData = $newsblock->getData();
        if (!empty($newsBlockData) && $newsBlockData['is_active']) { ?>
            <li class="newsblock">
                <span><strong>Created at: </strong><?php echo $newsBlockData['created_at'] ?></span>
                <h3><strong>Title: </strong><?php echo $newsBlockData['name'] ?></h3>
                <h5><strong>Short description: </strong><?php echo $newsBlockData['short_description'] ?></h5>
                <p><strong>Content: </strong><?php echo $newsBlockData['content'] ?></p>
            </li>
        <?php } ?>
    <?php } ?>
</ul>