<h1><q><?php echo $block->getData('title'); ?></q></h1>
<?php /** @var $block \Speroteck\Newsblock\Block\Widget\NewsblockList */ ?>
<ul class="newsblock-list">
    <?php /** @var $post \Speroteck\Newsblock\Model\Newsblock */ ?>
    <?php
    $newsblocks = $block->getNewsblocks();
    $newsBlockData = array();
    foreach ($newsblocks as $newsblock) {
        $newsBlockData = $newsblock->getData();
        if (!empty($newsBlockData) && $newsBlockData['is_active']) { ?>
            <li class="newsblock">
                <h3><strong>Title: </strong><?php echo $newsBlockData['name'] ?></h3>
                <h5><strong>Short description: </strong><?php echo $newsBlockData['short_description'] ?></h5>
            </li>
        <?php } ?>
    <?php } ?>
</ul>